name = "runart-decisiones"
main = "decisiones.js"
compatibility_date = "2025-10-01"

kv_namespaces = [
  { binding = "DECISIONES", id = "6418ac6ace59487c97bda9c3a50ab10e", preview_id = "e68d7a05dce645478e25c397d4c34c08" }
]

workers_dev = true

# Para rutas en dominio propio (descomentar y configurar cuando se necesite):
# routes = [
#   { pattern = "briefing.mi-dominio.com/api/*", zone_id = "ZONE_ID_AQUI" }
# ]
